version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:latest

jobs:
  build:
    executor: default
    steps:
      - checkout # check out the code in the project directory
      - run:
         name: Running Command
         command: |
           uptime
           curl $TELEGRAM_WEBHOOK/sendMessage?"chat_id=$CHATID&text=Below are the details of your build: %0A > BUILD_URL: ${CIRCLE_BUILD_URL} %0A > BUILD_NUMBER: ${CIRCLE_BUILD_NUM} %0A > TRIGGERER: ${CIRCLE_USERNAME}" # Send message to Telegram
