version: 2
jobs:
  build:
    docker:
      - image: centos7

    steps:
      - checkout

      - run:
          name: Greeting
          command: |
            sudo yum install -y httpd
            sudo systemctl start httpd.service

      - run:
          name: Print the Current Time
          command: date
