version: 2
jobs:
  build:
    docker:
      - image: httpd
    working_directory: /var/www/html  

    steps:
      - checkout

      - run:
          name: Checking apache server
          command: |
            uname -a
            apt update
            apt install curl -y
            apt-get install apache2 -y
            service --status-all
