version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Install HTTP
          command: |
            sudo apt-get install -y httpd
            sudo systemctl start httpd.service

      - run:
          name: Print the Current Time
          command: date
