version: 2.1
  
jobs:
  build:
    docker:
      - image: circleci/ubuntu
    parameters:
      webhook:
       description: Enter either your Webhook value or use the CircleCI UI to add your token under the 'TELEGRAM_WEBHOOK' env var
       type: string
       default: ${TELEGRAM_WEBHOOK}  

  steps:
    - checkout

    - run:
       name: Telegram Notification
       shell: /bin/bash
       command: |
        curl -X POST -H 'Content-type: application/json' $TELEGRAM_WEBHOOK/sendMessage?"chat_id=$CHATID&text=$TELEGRAM_MESSAGE"
