version: 2.1
  
jobs:
  build:
    docker:
      - image: circleci/ubuntu

  steps:
    - checkout

    - run:
       name: Telegram Notification
       shell: /bin/bash
       command: |
        curl https://api.telegram.org/bot1018984028:AAFo0hT75GJHrMITJi1CsKczSBZCm5K17xE/sendMessage?"chat_id=-391113057&text=config"
