version: 2
jobs:
  build:
    docker:
      - image: httpd
    working_directory: /var/www/html  

    steps:
      - checkout

     - run:
          name: Install Apache and start it
          command: |
            uname -a
            curl localhost
