version: 2.0
orbs:
  aws-cli: circleci/aws-cli@1.2.1
  aws-ecr: circleci/aws-ecr@6.9.1
jobs:
  deploy:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - aws-ecr/ecr-login:
          region: AWS_REGION
          account-url: AWS_ECR_ACCOUNT_URL
workflows:
  version: 2.0
  deploy:
    jobs:
      - deploy
