version: 2

workflows:
  version: 2
  release:
    jobs:
     - build

jobs: 
  build:
  
    docker:
      - image: 241099261431.dkr.ecr.us-east-1.amazonaws.com/pb/test:latest
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - run:
          name: Run commands
          command: |
              pwd
              ls
              
