version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Install HTTP
          command: |
            apt-get install apache2
            systemctl start httpd.service

      - run:
          name: Print the Current Time
          command: date
