version: 2
jobs:
  build:
    docker:
      - image: httpd
    working_directory: /var/www/html  

    steps:
      - checkout

      - run:
          name: Checking apache server
          command: |
            uname -a
            curl localhost
            service --status-all
