version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Install HTTP
          command: |
            apt update
            apt-get install apache2 -y
            
      - run:
          name: Print the Current Time
          command: date
