# You will have to create a Telegram bot first and add it to Telegram group.
# Telegram bot cannot send direct messages to the users for security and privacy reasons.
# Use BotFather bot of telegram to create a telegram bot and get API key.

version: 2.1

commands:
  notification:
    description: Send notification to Telegram group.
    parameters:
      webhook:
        default: ${TELEGRAM_WEBHOOK}
        description: Enter either your Webhook value or use the CircleCI UI to add
          your token under the 'TELEGRAM_WEBHOOK' env var
        type: string
    steps:
    - run:
        command: |
          temoji=%E2%9C%85
          curl $TELEGRAM_WEBHOOK/sendMessage?"chat_id=$CHATID&text=Below are the details of your build: %0A %F0%9F%95%9C Date: $(date) %0A $temoji BUILD_URL: ${CIRCLE_BUILD_URL} %0A $temoji BUILD_NUMBER: ${CIRCLE_BUILD_NUM} %0A $temoji TRIGGERER: ${CIRCLE_USERNAME}"
        name: Sending message to Telegram. 

executors:
  default:
    docker:
      - image: circleci/node:latest

jobs:
  build:
    executor: default
    steps:
      - checkout # check out the code in the project directory
      - notification # using Notification Command
